export const smartProps: {[index: string]: string} = {
  avatarUrl: 'internet.avatar',
  companyName: 'company.companyName',
  created: 'date.past',
  createdAt: 'date.past',
  createdOn: 'date.past',
  date: 'date.past',
  email: 'internet.email',
  emailAddress: 'internet.email',
  endDate: 'date.future',
  firstName: 'name.firstName',
  id: 'random.uuid',
  informalName: 'name.findName',
  initials: 'address.countryCode',
  lastName: 'name.lastName',
  middleName: 'name.firstName',
  name: 'name.findName',
  nickName: 'name.findName',
  oid: 'random.uuid',
  phone: 'phone.phoneNumber',
  position: 'name.jobTitle',
  primaryEmail: 'internet.email',
  startDate: 'date.past',
  username: 'internet.userName',
};
